export type RoutePoint = [number, number];

export type TransportType =
  | "train"
  | "plane"
  | "bus"
  | "ferry";

export type CityImportance = 1 | 2 | 3 | 4 | 5;

export type PopulationBand =
  | "small"
  | "medium"
  | "large"
  | "major";

export type City = {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  region: string;
  position: RoutePoint;
  population: number;
  enabled: boolean;
  importance: CityImportance;
};

export type ConnectionOverride = {
  fromCityId: string;
  toCityId: string;
  transport: TransportType;
  estimatedPriceEur: number;
  bidirectional: boolean;
  enabled: boolean;
  dataStatus: "prototype" | "verified";
  notes: string;
};

export const recommendationConfig = {
  recommendationCount: 5,
  candidatePoolSize: 30,
  minimumDistanceKm: 40,
  maximumDistanceKm: 650,
  samePopulationBandPenalty: 6,
  newPopulationBandBonus: 4,
  countryDiversityBonus: 5,
  distanceBandDiversityBonus: 5,
  forwardDirectionBonus: 22,
  strongBacktrackingPenalty: -32,
  trainWaypointSpacingKm: 75,
  trainRandomness: 0.06,
  planeCurveStrength: 0.18,
} as const;

export const cities: City[] = [
  {
    id: "brussels",
    name: "Brussels",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [50.85045, 4.34878],
    population: 1019022,
    enabled: true,
    importance: 5,
  },
  {
    id: "ghent",
    name: "Ghent",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [51.05000, 3.71667],
    population: 231493,
    enabled: true,
    importance: 5,
  },
  {
    id: "antwerp",
    name: "Antwerp",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [51.21989, 4.40346],
    population: 459805,
    enabled: true,
    importance: 4,
  },
  {
    id: "bruges",
    name: "Bruges",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [51.20892, 3.22424],
    population: 116709,
    enabled: true,
    importance: 4,
  },
  {
    id: "namur",
    name: "Namur",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [50.46690, 4.86746],
    population: 106284,
    enabled: true,
    importance: 4,
  },
  {
    id: "leuven",
    name: "Leuven",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [50.87959, 4.70093],
    population: 92892,
    enabled: true,
    importance: 4,
  },
  {
    id: "mechelen",
    name: "Mechelen",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [51.02574, 4.47762],
    population: 77530,
    enabled: true,
    importance: 4,
  },
  {
    id: "liege",
    name: "Liège",
    country: "Belgium",
    countryCode: "BE",
    region: "Western Europe",
    position: [50.63373, 5.56749],
    population: 182597,
    enabled: true,
    importance: 3,
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [48.85341, 2.34880],
    population: 2138551,
    enabled: true,
    importance: 5,
  },
  {
    id: "nice",
    name: "Nice",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.70313, 7.26608],
    population: 338620,
    enabled: true,
    importance: 5,
  },
  {
    id: "avignon",
    name: "Avignon",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.94834, 4.80892],
    population: 89769,
    enabled: true,
    importance: 5,
  },
  {
    id: "colmar",
    name: "Colmar",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [48.08333, 7.36667],
    population: 65405,
    enabled: true,
    importance: 5,
  },
  {
    id: "saint-malo",
    name: "Saint-Malo",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [48.65000, -2.01667],
    population: 50676,
    enabled: true,
    importance: 5,
  },
  {
    id: "annecy",
    name: "Annecy",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [45.90000, 6.11667],
    population: 49232,
    enabled: true,
    importance: 5,
  },
  {
    id: "marseille",
    name: "Marseille",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.29695, 5.38107],
    population: 794811,
    enabled: true,
    importance: 4,
  },
  {
    id: "lyon",
    name: "Lyon",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [45.74846, 4.84671],
    population: 472317,
    enabled: true,
    importance: 4,
  },
  {
    id: "toulouse",
    name: "Toulouse",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.60426, 1.44367],
    population: 433055,
    enabled: true,
    importance: 4,
  },
  {
    id: "strasbourg",
    name: "Strasbourg",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [48.58392, 7.74553],
    population: 274845,
    enabled: true,
    importance: 4,
  },
  {
    id: "bordeaux",
    name: "Bordeaux",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [44.84044, -0.58050],
    population: 231844,
    enabled: true,
    importance: 4,
  },
  {
    id: "reims",
    name: "Reims",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [49.25000, 4.03333],
    population: 196565,
    enabled: true,
    importance: 4,
  },
  {
    id: "grenoble",
    name: "Grenoble",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [45.16667, 5.71667],
    population: 158552,
    enabled: true,
    importance: 4,
  },
  {
    id: "dijon",
    name: "Dijon",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [47.31667, 5.01667],
    population: 149782,
    enabled: true,
    importance: 4,
  },
  {
    id: "nimes",
    name: "Nîmes",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.83333, 4.35000],
    population: 148236,
    enabled: true,
    importance: 4,
  },
  {
    id: "aix-en-provence",
    name: "Aix-en-Provence",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.52830, 5.44973],
    population: 146821,
    enabled: true,
    importance: 4,
  },
  {
    id: "tours",
    name: "Tours",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [47.38333, 0.68333],
    population: 141621,
    enabled: true,
    importance: 4,
  },
  {
    id: "besancon",
    name: "Besançon",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [47.24878, 6.01815],
    population: 128426,
    enabled: true,
    importance: 4,
  },
  {
    id: "rouen",
    name: "Rouen",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [49.44313, 1.09932],
    population: 112787,
    enabled: true,
    importance: 4,
  },
  {
    id: "caen",
    name: "Caen",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [49.18585, -0.35912],
    population: 110624,
    enabled: true,
    importance: 4,
  },
  {
    id: "la-rochelle",
    name: "La Rochelle",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [46.16667, -1.15000],
    population: 76810,
    enabled: true,
    importance: 4,
  },
  {
    id: "cannes",
    name: "Cannes",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.55135, 7.01275],
    population: 70011,
    enabled: true,
    importance: 4,
  },
  {
    id: "arles",
    name: "Arles",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.67681, 4.63031],
    population: 53431,
    enabled: true,
    importance: 4,
  },
  {
    id: "nantes",
    name: "Nantes",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [47.21725, -1.55336],
    population: 277269,
    enabled: true,
    importance: 3,
  },
  {
    id: "montpellier",
    name: "Montpellier",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [43.61092, 3.87723],
    population: 248252,
    enabled: true,
    importance: 3,
  },
  {
    id: "lille",
    name: "Lille",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [50.63297, 3.05858],
    population: 228328,
    enabled: true,
    importance: 3,
  },
  {
    id: "le-havre",
    name: "Le Havre",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [49.49380, 0.10767],
    population: 185972,
    enabled: true,
    importance: 3,
  },
  {
    id: "angers",
    name: "Angers",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [47.46667, -0.55000],
    population: 168279,
    enabled: true,
    importance: 3,
  },
  {
    id: "brest",
    name: "Brest",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [48.40000, -4.48333],
    population: 144899,
    enabled: true,
    importance: 3,
  },
  {
    id: "amiens",
    name: "Amiens",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [49.90000, 2.30000],
    population: 143086,
    enabled: true,
    importance: 3,
  },
  {
    id: "clermont-ferrand",
    name: "Clermont-Ferrand",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [45.77966, 3.08628],
    population: 138681,
    enabled: true,
    importance: 3,
  },
  {
    id: "orleans",
    name: "Orléans",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [47.90289, 1.90389],
    population: 124149,
    enabled: true,
    importance: 3,
  },
  {
    id: "metz",
    name: "Metz",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [49.11911, 6.17269],
    population: 123914,
    enabled: true,
    importance: 3,
  },
  {
    id: "mulhouse",
    name: "Mulhouse",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [47.75000, 7.33333],
    population: 111430,
    enabled: true,
    importance: 3,
  },
  {
    id: "perpignan",
    name: "Perpignan",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [42.69764, 2.89541],
    population: 110706,
    enabled: true,
    importance: 3,
  },
  {
    id: "nancy",
    name: "Nancy",
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    position: [48.68439, 6.18496],
    population: 105334,
    enabled: true,
    importance: 3,
  },
  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    region: "Western Europe",
    position: [53.33306, -6.24889],
    population: 1024027,
    enabled: true,
    importance: 5,
  },
  {
    id: "cork",
    name: "Cork",
    country: "Ireland",
    countryCode: "IE",
    region: "Western Europe",
    position: [51.89797, -8.47061],
    population: 190384,
    enabled: true,
    importance: 5,
  },
  {
    id: "galway",
    name: "Galway",
    country: "Ireland",
    countryCode: "IE",
    region: "Western Europe",
    position: [53.27194, -9.04889],
    population: 70686,
    enabled: true,
    importance: 5,
  },
  {
    id: "kilkenny",
    name: "Kilkenny",
    country: "Ireland",
    countryCode: "IE",
    region: "Western Europe",
    position: [52.65417, -7.25222],
    population: 21589,
    enabled: true,
    importance: 4,
  },
  {
    id: "limerick",
    name: "Limerick",
    country: "Ireland",
    countryCode: "IE",
    region: "Western Europe",
    position: [52.66472, -8.62306],
    population: 90054,
    enabled: true,
    importance: 3,
  },
  {
    id: "waterford",
    name: "Waterford",
    country: "Ireland",
    countryCode: "IE",
    region: "Western Europe",
    position: [52.25833, -7.11194],
    population: 47904,
    enabled: true,
    importance: 3,
  },
  {
    id: "drogheda",
    name: "Drogheda",
    country: "Ireland",
    countryCode: "IE",
    region: "Western Europe",
    position: [53.71889, -6.34778],
    population: 33441,
    enabled: true,
    importance: 2,
  },
  {
    id: "luxembourg",
    name: "Luxembourg",
    country: "Luxembourg",
    countryCode: "LU",
    region: "Western Europe",
    position: [49.61167, 6.13000],
    population: 76684,
    enabled: true,
    importance: 3,
  },
  {
    id: "esch-sur-alzette",
    name: "Esch-sur-Alzette",
    country: "Luxembourg",
    countryCode: "LU",
    region: "Western Europe",
    position: [49.49583, 5.98056],
    population: 28228,
    enabled: true,
    importance: 2,
  },
  {
    id: "monaco",
    name: "Monaco",
    country: "Monaco",
    countryCode: "MC",
    region: "Western Europe",
    position: [43.73333, 7.41667],
    population: 32965,
    enabled: true,
    importance: 5,
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [52.37403, 4.88969],
    population: 741636,
    enabled: true,
    importance: 5,
  },
  {
    id: "maastricht",
    name: "Maastricht",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [50.84833, 5.68889],
    population: 122378,
    enabled: true,
    importance: 5,
  },
  {
    id: "delft",
    name: "Delft",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [52.00667, 4.35556],
    population: 95060,
    enabled: true,
    importance: 5,
  },
  {
    id: "utrecht",
    name: "Utrecht",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [52.09083, 5.12222],
    population: 290529,
    enabled: true,
    importance: 4,
  },
  {
    id: "groningen",
    name: "Groningen",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [53.21917, 6.56667],
    population: 181194,
    enabled: true,
    importance: 4,
  },
  {
    id: "haarlem",
    name: "Haarlem",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [52.38084, 4.63683],
    population: 147590,
    enabled: true,
    importance: 4,
  },
  {
    id: "s-hertogenbosch",
    name: "'s-Hertogenbosch",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [51.69917, 5.30417],
    population: 134520,
    enabled: true,
    importance: 4,
  },
  {
    id: "leiden",
    name: "Leiden",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [52.15833, 4.49306],
    population: 119713,
    enabled: true,
    importance: 4,
  },
  {
    id: "rotterdam",
    name: "Rotterdam",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [51.92250, 4.47917],
    population: 598199,
    enabled: true,
    importance: 3,
  },
  {
    id: "eindhoven",
    name: "Eindhoven",
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    position: [51.44083, 5.47778],
    population: 209620,
    enabled: true,
    importance: 3,
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [51.50853, -0.12574],
    population: 7556900,
    enabled: true,
    importance: 5,
  },
  {
    id: "edinburgh",
    name: "Edinburgh",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [55.95206, -3.19648],
    population: 435791,
    enabled: true,
    importance: 5,
  },
  {
    id: "oxford",
    name: "Oxford",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [51.75222, -1.25596],
    population: 154566,
    enabled: true,
    importance: 5,
  },
  {
    id: "york",
    name: "York",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [53.95763, -1.08271],
    population: 144202,
    enabled: true,
    importance: 5,
  },
  {
    id: "cambridge",
    name: "Cambridge",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [52.20000, 0.11667],
    population: 128488,
    enabled: true,
    importance: 5,
  },
  {
    id: "bath",
    name: "Bath",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [51.37510, -2.36172],
    population: 93238,
    enabled: true,
    importance: 5,
  },
  {
    id: "birmingham",
    name: "Birmingham",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [52.48142, -1.89983],
    population: 984333,
    enabled: true,
    importance: 4,
  },
  {
    id: "glasgow",
    name: "Glasgow",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [55.86515, -4.25763],
    population: 610268,
    enabled: true,
    importance: 4,
  },
  {
    id: "liverpool",
    name: "Liverpool",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [53.41058, -2.97794],
    population: 468945,
    enabled: true,
    importance: 4,
  },
  {
    id: "leeds",
    name: "Leeds",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [53.79648, -1.54785],
    population: 455123,
    enabled: true,
    importance: 4,
  },
  {
    id: "manchester",
    name: "Manchester",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [53.48095, -2.23743],
    population: 395515,
    enabled: true,
    importance: 4,
  },
  {
    id: "cardiff",
    name: "Cardiff",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [51.48000, -3.18000],
    population: 302139,
    enabled: true,
    importance: 4,
  },
  {
    id: "newcastle-upon-tyne",
    name: "Newcastle upon Tyne",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [54.97328, -1.61396],
    population: 192382,
    enabled: true,
    importance: 4,
  },
  {
    id: "brighton",
    name: "Brighton",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [50.82838, -0.13947],
    population: 139001,
    enabled: true,
    importance: 4,
  },
  {
    id: "chester",
    name: "Chester",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [53.19050, -2.89189],
    population: 77040,
    enabled: true,
    importance: 4,
  },
  {
    id: "canterbury",
    name: "Canterbury",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [51.27904, 1.07992],
    population: 46978,
    enabled: true,
    importance: 4,
  },
  {
    id: "inverness",
    name: "Inverness",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [57.47908, -4.22398],
    population: 40755,
    enabled: true,
    importance: 4,
  },
  {
    id: "stirling",
    name: "Stirling",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [56.11903, -3.93682],
    population: 33012,
    enabled: true,
    importance: 4,
  },
  {
    id: "sheffield",
    name: "Sheffield",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [53.38297, -1.46590],
    population: 447047,
    enabled: true,
    importance: 3,
  },
  {
    id: "bristol",
    name: "Bristol",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [51.45523, -2.59665],
    population: 430713,
    enabled: true,
    importance: 3,
  },
  {
    id: "belfast",
    name: "Belfast",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [54.59682, -5.92541],
    population: 274770,
    enabled: true,
    importance: 3,
  },
  {
    id: "nottingham",
    name: "Nottingham",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [52.95360, -1.15047],
    population: 246654,
    enabled: true,
    importance: 3,
  },
  {
    id: "southampton",
    name: "Southampton",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [50.90395, -1.40428],
    population: 246201,
    enabled: true,
    importance: 3,
  },
  {
    id: "portsmouth",
    name: "Portsmouth",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [50.79899, -1.09125],
    population: 194150,
    enabled: true,
    importance: 3,
  },
  {
    id: "aberdeen",
    name: "Aberdeen",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [57.14369, -2.09814],
    population: 183790,
    enabled: true,
    importance: 3,
  },
  {
    id: "swansea",
    name: "Swansea",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    position: [51.62079, -3.94323],
    population: 170883,
    enabled: true,
    importance: 3,
  },
  {
    id: "andorra-la-vella",
    name: "Andorra la Vella",
    country: "Andorra",
    countryCode: "AD",
    region: "Southern Europe",
    position: [42.50779, 1.52109],
    population: 20430,
    enabled: true,
    importance: 4,
  },
  {
    id: "les-escaldes",
    name: "les Escaldes",
    country: "Andorra",
    countryCode: "AD",
    region: "Southern Europe",
    position: [42.50729, 1.53414],
    population: 15853,
    enabled: true,
    importance: 3,
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [41.89193, 12.51133],
    population: 2318895,
    enabled: true,
    importance: 5,
  },
  {
    id: "milan",
    name: "Milan",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.46427, 9.18951],
    population: 1236837,
    enabled: true,
    importance: 5,
  },
  {
    id: "naples",
    name: "Naples",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [40.85631, 14.24641],
    population: 959470,
    enabled: true,
    importance: 5,
  },
  {
    id: "florence",
    name: "Florence",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [43.77925, 11.24626],
    population: 349296,
    enabled: true,
    importance: 5,
  },
  {
    id: "catania",
    name: "Catania",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [37.49223, 15.07041],
    population: 290927,
    enabled: true,
    importance: 5,
  },
  {
    id: "trieste",
    name: "Trieste",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.64325, 13.79030],
    population: 187056,
    enabled: true,
    importance: 5,
  },
  {
    id: "syracuse",
    name: "Syracuse",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [37.08415, 15.27628],
    population: 97472,
    enabled: true,
    importance: 5,
  },
  {
    id: "ravenna",
    name: "Ravenna",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.41344, 12.20121],
    population: 80868,
    enabled: true,
    importance: 5,
  },
  {
    id: "lecce",
    name: "Lecce",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [40.35481, 18.17244],
    population: 80695,
    enabled: true,
    importance: 5,
  },
  {
    id: "pisa",
    name: "Pisa",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [43.70853, 10.40360],
    population: 77007,
    enabled: true,
    importance: 5,
  },
  {
    id: "matera",
    name: "Matera",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [40.66599, 16.60463],
    population: 54891,
    enabled: true,
    importance: 5,
  },
  {
    id: "venice",
    name: "Venice",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.43713, 12.33265],
    population: 51298,
    enabled: true,
    importance: 5,
  },
  {
    id: "siena",
    name: "Siena",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [43.31822, 11.33064],
    population: 42867,
    enabled: true,
    importance: 5,
  },
  {
    id: "turin",
    name: "Turin",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.07049, 7.68682],
    population: 870456,
    enabled: true,
    importance: 4,
  },
  {
    id: "palermo",
    name: "Palermo",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [38.13205, 13.33561],
    population: 648260,
    enabled: true,
    importance: 4,
  },
  {
    id: "bologna",
    name: "Bologna",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.49381, 11.33875],
    population: 366133,
    enabled: true,
    importance: 4,
  },
  {
    id: "verona",
    name: "Verona",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.42990, 10.98444],
    population: 219103,
    enabled: true,
    importance: 4,
  },
  {
    id: "padua",
    name: "Padua",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.40797, 11.88586],
    population: 203725,
    enabled: true,
    importance: 4,
  },
  {
    id: "modena",
    name: "Modena",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.64783, 10.92539],
    population: 158886,
    enabled: true,
    importance: 4,
  },
  {
    id: "parma",
    name: "Parma",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.79935, 10.32618],
    population: 146299,
    enabled: true,
    importance: 4,
  },
  {
    id: "salerno",
    name: "Salerno",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [40.67545, 14.79328],
    population: 125797,
    enabled: true,
    importance: 4,
  },
  {
    id: "perugia",
    name: "Perugia",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [43.11220, 12.38878],
    population: 120137,
    enabled: true,
    importance: 4,
  },
  {
    id: "rimini",
    name: "Rimini",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.05755, 12.56528],
    population: 118673,
    enabled: true,
    importance: 4,
  },
  {
    id: "bergamo",
    name: "Bergamo",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.69601, 9.66721],
    population: 114162,
    enabled: true,
    importance: 4,
  },
  {
    id: "vicenza",
    name: "Vicenza",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.54672, 11.54750],
    population: 107129,
    enabled: true,
    importance: 4,
  },
  {
    id: "bolzano",
    name: "Bolzano",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [46.49067, 11.33982],
    population: 99049,
    enabled: true,
    importance: 4,
  },
  {
    id: "ferrara",
    name: "Ferrara",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.83804, 11.62057],
    population: 92802,
    enabled: true,
    importance: 4,
  },
  {
    id: "la-spezia",
    name: "La Spezia",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.10300, 9.82375],
    population: 88491,
    enabled: true,
    importance: 4,
  },
  {
    id: "como",
    name: "Como",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.80819, 9.08320],
    population: 81975,
    enabled: true,
    importance: 4,
  },
  {
    id: "lucca",
    name: "Lucca",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [43.84369, 10.50447],
    population: 81748,
    enabled: true,
    importance: 4,
  },
  {
    id: "trento",
    name: "Trento",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [46.06787, 11.12108],
    population: 80425,
    enabled: true,
    importance: 4,
  },
  {
    id: "arezzo",
    name: "Arezzo",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [43.46276, 11.88068],
    population: 76346,
    enabled: true,
    importance: 4,
  },
  {
    id: "mantua",
    name: "Mantua",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.16031, 10.79784],
    population: 39260,
    enabled: true,
    importance: 4,
  },
  {
    id: "genoa",
    name: "Genoa",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [44.42640, 8.91519],
    population: 580223,
    enabled: true,
    importance: 3,
  },
  {
    id: "bari",
    name: "Bari",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [41.11148, 16.85540],
    population: 277387,
    enabled: true,
    importance: 3,
  },
  {
    id: "brescia",
    name: "Brescia",
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    position: [45.53558, 10.21472],
    population: 184826,
    enabled: true,
    importance: 3,
  },
  {
    id: "valletta",
    name: "Valletta",
    country: "Malta",
    countryCode: "MT",
    region: "Southern Europe",
    position: [35.89972, 14.51472],
    population: 6794,
    enabled: true,
    importance: 5,
  },
  {
    id: "birkirkara",
    name: "Birkirkara",
    country: "Malta",
    countryCode: "MT",
    region: "Southern Europe",
    position: [35.89722, 14.46111],
    population: 21676,
    enabled: true,
    importance: 2,
  },
  {
    id: "qormi",
    name: "Qormi",
    country: "Malta",
    countryCode: "MT",
    region: "Southern Europe",
    position: [35.87601, 14.47200],
    population: 18230,
    enabled: true,
    importance: 2,
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [38.71667, -9.13333],
    population: 517802,
    enabled: true,
    importance: 5,
  },
  {
    id: "porto",
    name: "Porto",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [41.14961, -8.61099],
    population: 249633,
    enabled: true,
    importance: 5,
  },
  {
    id: "coimbra",
    name: "Coimbra",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [40.20564, -8.41955],
    population: 106582,
    enabled: true,
    importance: 5,
  },
  {
    id: "evora",
    name: "Évora",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [38.56667, -7.90000],
    population: 55620,
    enabled: true,
    importance: 5,
  },
  {
    id: "guimaraes",
    name: "Guimarães",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [41.44443, -8.29619],
    population: 40604,
    enabled: true,
    importance: 5,
  },
  {
    id: "sintra",
    name: "Sintra",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [38.80097, -9.37826],
    population: 26193,
    enabled: true,
    importance: 5,
  },
  {
    id: "braga",
    name: "Braga",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [41.55032, -8.42005],
    population: 121394,
    enabled: true,
    importance: 4,
  },
  {
    id: "funchal",
    name: "Funchal",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [32.66568, -16.92547],
    population: 100847,
    enabled: true,
    importance: 4,
  },
  {
    id: "aveiro",
    name: "Aveiro",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [40.64427, -8.64554],
    population: 54162,
    enabled: true,
    importance: 4,
  },
  {
    id: "lagos",
    name: "Lagos",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [37.10202, -8.67422],
    population: 18831,
    enabled: true,
    importance: 4,
  },
  {
    id: "setubal",
    name: "Setúbal",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [38.52440, -8.88820],
    population: 117110,
    enabled: true,
    importance: 3,
  },
  {
    id: "faro",
    name: "Faro",
    country: "Portugal",
    countryCode: "PT",
    region: "Southern Europe",
    position: [37.01937, -7.93223],
    population: 41355,
    enabled: true,
    importance: 3,
  },
  {
    id: "san-marino",
    name: "San Marino",
    country: "San Marino",
    countryCode: "SM",
    region: "Southern Europe",
    position: [43.93667, 12.44639],
    population: 4500,
    enabled: true,
    importance: 4,
  },
  {
    id: "madrid",
    name: "Madrid",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [40.41650, -3.70256],
    population: 3255944,
    enabled: true,
    importance: 5,
  },
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [41.38879, 2.15899],
    population: 1621537,
    enabled: true,
    importance: 5,
  },
  {
    id: "seville",
    name: "Seville",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [37.38283, -5.97317],
    population: 703206,
    enabled: true,
    importance: 5,
  },
  {
    id: "cordoba",
    name: "Córdoba",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [37.89155, -4.77275],
    population: 328428,
    enabled: true,
    importance: 5,
  },
  {
    id: "santiago-de-compostela",
    name: "Santiago de Compostela",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [42.88052, -8.54569],
    population: 95092,
    enabled: true,
    importance: 5,
  },
  {
    id: "toledo",
    name: "Toledo",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [39.85810, -4.02263],
    population: 82291,
    enabled: true,
    importance: 5,
  },
  {
    id: "valencia",
    name: "Valencia",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [39.46975, -0.37739],
    population: 814208,
    enabled: true,
    importance: 4,
  },
  {
    id: "malaga",
    name: "Malaga",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [36.72016, -4.42034],
    population: 568305,
    enabled: true,
    importance: 4,
  },
  {
    id: "palma",
    name: "Palma",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [39.56939, 2.65024],
    population: 401270,
    enabled: true,
    importance: 4,
  },
  {
    id: "bilbao",
    name: "Bilbao",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [43.26271, -2.92528],
    population: 354860,
    enabled: true,
    importance: 4,
  },
  {
    id: "a-coruna",
    name: "A Coruña",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [43.37135, -8.39600],
    population: 246056,
    enabled: true,
    importance: 4,
  },
  {
    id: "granada",
    name: "Granada",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [37.18817, -3.60667],
    population: 234325,
    enabled: true,
    importance: 4,
  },
  {
    id: "oviedo",
    name: "Oviedo",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [43.36029, -5.84476],
    population: 224005,
    enabled: true,
    importance: 4,
  },
  {
    id: "pamplona",
    name: "Pamplona",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [42.81687, -1.64323],
    population: 198491,
    enabled: true,
    importance: 4,
  },
  {
    id: "san-sebastian",
    name: "San Sebastian",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [43.31283, -1.97499],
    population: 185357,
    enabled: true,
    importance: 4,
  },
  {
    id: "santander",
    name: "Santander",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [43.46472, -3.80444],
    population: 182700,
    enabled: true,
    importance: 4,
  },
  {
    id: "salamanca",
    name: "Salamanca",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [40.96882, -5.66388],
    population: 155619,
    enabled: true,
    importance: 4,
  },
  {
    id: "tarragona",
    name: "Tarragona",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [41.11667, 1.25000],
    population: 140323,
    enabled: true,
    importance: 4,
  },
  {
    id: "cadiz",
    name: "Cádiz",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [36.52978, -6.29465],
    population: 126766,
    enabled: true,
    importance: 4,
  },
  {
    id: "girona",
    name: "Girona",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [41.98311, 2.82493],
    population: 96188,
    enabled: true,
    importance: 4,
  },
  {
    id: "segovia",
    name: "Segovia",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [40.94808, -4.11839],
    population: 56660,
    enabled: true,
    importance: 4,
  },
  {
    id: "cuenca",
    name: "Cuenca",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [40.06667, -2.13333],
    population: 55866,
    enabled: true,
    importance: 4,
  },
  {
    id: "ronda",
    name: "Ronda",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [36.74231, -5.16709],
    population: 36827,
    enabled: true,
    importance: 4,
  },
  {
    id: "zaragoza",
    name: "Zaragoza",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [41.65606, -0.87734],
    population: 674317,
    enabled: true,
    importance: 3,
  },
  {
    id: "murcia",
    name: "Murcia",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [37.98704, -1.13004],
    population: 436870,
    enabled: true,
    importance: 3,
  },
  {
    id: "alicante",
    name: "Alicante",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [38.34517, -0.48149],
    population: 334757,
    enabled: true,
    importance: 3,
  },
  {
    id: "valladolid",
    name: "Valladolid",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [41.65518, -4.72372],
    population: 317864,
    enabled: true,
    importance: 3,
  },
  {
    id: "vigo",
    name: "Vigo",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [42.23282, -8.72264],
    population: 297332,
    enabled: true,
    importance: 3,
  },
  {
    id: "gijon",
    name: "Gijón",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [43.53573, -5.66152],
    population: 277554,
    enabled: true,
    importance: 3,
  },
  {
    id: "jerez-de-la-frontera",
    name: "Jerez de la Frontera",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [36.68645, -6.13606],
    population: 207532,
    enabled: true,
    importance: 3,
  },
  {
    id: "almeria",
    name: "Almería",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [36.83814, -2.45974],
    population: 188810,
    enabled: true,
    importance: 3,
  },
  {
    id: "marbella",
    name: "Marbella",
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    position: [36.51543, -4.88583],
    population: 134623,
    enabled: true,
    importance: 3,
  },
  {
    id: "vatican-city",
    name: "Vatican City",
    country: "Vatican City",
    countryCode: "VA",
    region: "Southern Europe",
    position: [41.90268, 12.45414],
    population: 829,
    enabled: true,
    importance: 5,
  },
  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [48.20849, 16.37208],
    population: 1691468,
    enabled: true,
    importance: 5,
  },
  {
    id: "graz",
    name: "Graz",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [47.06667, 15.45000],
    population: 222326,
    enabled: true,
    importance: 5,
  },
  {
    id: "salzburg",
    name: "Salzburg",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [47.79941, 13.04399],
    population: 150269,
    enabled: true,
    importance: 5,
  },
  {
    id: "innsbruck",
    name: "Innsbruck",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [47.26266, 11.39454],
    population: 112467,
    enabled: true,
    importance: 4,
  },
  {
    id: "bregenz",
    name: "Bregenz",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [47.50311, 9.74710],
    population: 27611,
    enabled: true,
    importance: 4,
  },
  {
    id: "krems-an-der-donau",
    name: "Krems an der Donau",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [48.40921, 15.61415],
    population: 23932,
    enabled: true,
    importance: 4,
  },
  {
    id: "linz",
    name: "Linz",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [48.30639, 14.28611],
    population: 181162,
    enabled: true,
    importance: 3,
  },
  {
    id: "klagenfurt",
    name: "Klagenfurt",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [46.62472, 14.30528],
    population: 90610,
    enabled: true,
    importance: 3,
  },
  {
    id: "villach",
    name: "Villach",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [46.61028, 13.85583],
    population: 58882,
    enabled: true,
    importance: 3,
  },
  {
    id: "sankt-polten",
    name: "Sankt Pölten",
    country: "Austria",
    countryCode: "AT",
    region: "Central Europe",
    position: [48.20000, 15.63333],
    population: 49001,
    enabled: true,
    importance: 3,
  },
  {
    id: "prague",
    name: "Prague",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [50.08804, 14.42076],
    population: 1165581,
    enabled: true,
    importance: 5,
  },
  {
    id: "brno",
    name: "Brno",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [49.19522, 16.60796],
    population: 369559,
    enabled: true,
    importance: 5,
  },
  {
    id: "karlovy-vary",
    name: "Karlovy Vary",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [50.23271, 12.87117],
    population: 51807,
    enabled: true,
    importance: 5,
  },
  {
    id: "kutna-hora",
    name: "Kutná Hora",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [49.94839, 15.26816],
    population: 21280,
    enabled: true,
    importance: 5,
  },
  {
    id: "plzen",
    name: "Plzeň",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [49.74747, 13.37759],
    population: 164180,
    enabled: true,
    importance: 4,
  },
  {
    id: "olomouc",
    name: "Olomouc",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [49.59552, 17.25175],
    population: 101268,
    enabled: true,
    importance: 4,
  },
  {
    id: "ceske-budejovice",
    name: "České Budějovice",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [48.97447, 14.47434],
    population: 96053,
    enabled: true,
    importance: 4,
  },
  {
    id: "ostrava",
    name: "Ostrava",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [49.83465, 18.28204],
    population: 313088,
    enabled: true,
    importance: 3,
  },
  {
    id: "liberec",
    name: "Liberec",
    country: "Czechia",
    countryCode: "CZ",
    region: "Central Europe",
    position: [50.76711, 15.05619],
    population: 97770,
    enabled: true,
    importance: 3,
  },
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [52.52437, 13.41053],
    population: 3426354,
    enabled: true,
    importance: 5,
  },
  {
    id: "munich",
    name: "Munich",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [48.13743, 11.57549],
    population: 1260391,
    enabled: true,
    importance: 5,
  },
  {
    id: "lubeck",
    name: "Lübeck",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [53.86893, 10.68729],
    population: 212207,
    enabled: true,
    importance: 5,
  },
  {
    id: "potsdam",
    name: "Potsdam",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [52.39886, 13.06566],
    population: 145292,
    enabled: true,
    importance: 5,
  },
  {
    id: "heidelberg",
    name: "Heidelberg",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [49.40768, 8.69079],
    population: 143345,
    enabled: true,
    importance: 5,
  },
  {
    id: "regensburg",
    name: "Regensburg",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [49.01513, 12.10161],
    population: 129151,
    enabled: true,
    importance: 5,
  },
  {
    id: "trier",
    name: "Trier",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [49.75565, 6.63935],
    population: 100129,
    enabled: true,
    importance: 5,
  },
  {
    id: "bamberg",
    name: "Bamberg",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [49.89873, 10.90067],
    population: 70047,
    enabled: true,
    importance: 5,
  },
  {
    id: "weimar",
    name: "Weimar",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [50.98030, 11.32903],
    population: 64727,
    enabled: true,
    importance: 5,
  },
  {
    id: "hamburg",
    name: "Hamburg",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [53.57532, 10.01534],
    population: 1739117,
    enabled: true,
    importance: 4,
  },
  {
    id: "cologne",
    name: "Cologne",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [50.93333, 6.95000],
    population: 963395,
    enabled: true,
    importance: 4,
  },
  {
    id: "dusseldorf",
    name: "Düsseldorf",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [51.22172, 6.77616],
    population: 573057,
    enabled: true,
    importance: 4,
  },
  {
    id: "bremen",
    name: "Bremen",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [53.07516, 8.80777],
    population: 546501,
    enabled: true,
    importance: 4,
  },
  {
    id: "nuremberg",
    name: "Nuremberg",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [49.45421, 11.07752],
    population: 499237,
    enabled: true,
    importance: 4,
  },
  {
    id: "dresden",
    name: "Dresden",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [51.05089, 13.73832],
    population: 486854,
    enabled: true,
    importance: 4,
  },
  {
    id: "bonn",
    name: "Bonn",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [50.73438, 7.09549],
    population: 313125,
    enabled: true,
    importance: 4,
  },
  {
    id: "munster",
    name: "Münster",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [51.96236, 7.62571],
    population: 270184,
    enabled: true,
    importance: 4,
  },
  {
    id: "aachen",
    name: "Aachen",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [50.77664, 6.08342],
    population: 265208,
    enabled: true,
    importance: 4,
  },
  {
    id: "augsburg",
    name: "Augsburg",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [48.37154, 10.89851],
    population: 259196,
    enabled: true,
    importance: 4,
  },
  {
    id: "freiburg-im-breisgau",
    name: "Freiburg im Breisgau",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [47.99590, 7.85222],
    population: 215966,
    enabled: true,
    importance: 4,
  },
  {
    id: "erfurt",
    name: "Erfurt",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [50.97870, 11.03283],
    population: 203254,
    enabled: true,
    importance: 4,
  },
  {
    id: "mainz",
    name: "Mainz",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [49.98419, 8.27910],
    population: 184997,
    enabled: true,
    importance: 4,
  },
  {
    id: "wurzburg",
    name: "Würzburg",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [49.79391, 9.95121],
    population: 133731,
    enabled: true,
    importance: 4,
  },
  {
    id: "koblenz",
    name: "Koblenz",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [50.35357, 7.57883],
    population: 107319,
    enabled: true,
    importance: 4,
  },
  {
    id: "gorlitz",
    name: "Görlitz",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [51.15518, 14.98853],
    population: 57751,
    enabled: true,
    importance: 4,
  },
  {
    id: "baden-baden",
    name: "Baden-Baden",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [48.76060, 8.23975],
    population: 54239,
    enabled: true,
    importance: 4,
  },
  {
    id: "garmisch-partenkirchen",
    name: "Garmisch-Partenkirchen",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [47.49209, 11.09576],
    population: 26022,
    enabled: true,
    importance: 4,
  },
  {
    id: "frankfurt",
    name: "Frankfurt",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [50.11552, 8.68417],
    population: 650000,
    enabled: true,
    importance: 3,
  },
  {
    id: "stuttgart",
    name: "Stuttgart",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [48.78232, 9.17702],
    population: 589793,
    enabled: true,
    importance: 3,
  },
  {
    id: "hannover",
    name: "Hannover",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [52.37052, 9.73322],
    population: 515140,
    enabled: true,
    importance: 3,
  },
  {
    id: "leipzig",
    name: "Leipzig",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [51.33962, 12.37129],
    population: 504971,
    enabled: true,
    importance: 3,
  },
  {
    id: "kiel",
    name: "Kiel",
    country: "Germany",
    countryCode: "DE",
    region: "Central Europe",
    position: [54.32133, 10.13489],
    population: 232758,
    enabled: true,
    importance: 3,
  },
  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    region: "Central Europe",
    position: [47.49801, 19.03991],
    population: 1741041,
    enabled: true,
    importance: 5,
  },
  {
    id: "eger",
    name: "Eger",
    country: "Hungary",
    countryCode: "HU",
    region: "Central Europe",
    position: [47.90265, 20.37329],
    population: 56647,
    enabled: true,
    importance: 5,
  },
  {
    id: "szeged",
    name: "Szeged",
    country: "Hungary",
    countryCode: "HU",
    region: "Central Europe",
    position: [46.25300, 20.14824],
    population: 164883,
    enabled: true,
    importance: 4,
  },
  {
    id: "pecs",
    name: "Pécs",
    country: "Hungary",
    countryCode: "HU",
    region: "Central Europe",
    position: [46.08333, 18.23333],
    population: 156649,
    enabled: true,
    importance: 4,
  },
  {
    id: "gyor",
    name: "Győr",
    country: "Hungary",
    countryCode: "HU",
    region: "Central Europe",
    position: [47.68333, 17.63512],
    population: 128265,
    enabled: true,
    importance: 4,
  },
  {
    id: "debrecen",
    name: "Debrecen",
    country: "Hungary",
    countryCode: "HU",
    region: "Central Europe",
    position: [47.53333, 21.63333],
    population: 204124,
    enabled: true,
    importance: 3,
  },
  {
    id: "miskolc",
    name: "Miskolc",
    country: "Hungary",
    countryCode: "HU",
    region: "Central Europe",
    position: [48.10000, 20.78333],
    population: 172637,
    enabled: true,
    importance: 3,
  },
  {
    id: "vaduz",
    name: "Vaduz",
    country: "Liechtenstein",
    countryCode: "LI",
    region: "Central Europe",
    position: [47.14151, 9.52154],
    population: 5197,
    enabled: true,
    importance: 4,
  },
  {
    id: "krakow",
    name: "Krakow",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [50.06143, 19.93658],
    population: 755050,
    enabled: true,
    importance: 5,
  },
  {
    id: "wroc-aw",
    name: "Wrocław",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [51.10000, 17.03333],
    population: 634893,
    enabled: true,
    importance: 5,
  },
  {
    id: "gdansk",
    name: "Gdańsk",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [54.35205, 18.64637],
    population: 461865,
    enabled: true,
    importance: 5,
  },
  {
    id: "torun",
    name: "Toruń",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [53.01375, 18.59814],
    population: 208717,
    enabled: true,
    importance: 5,
  },
  {
    id: "zakopane",
    name: "Zakopane",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [49.29899, 19.94885],
    population: 27580,
    enabled: true,
    importance: 5,
  },
  {
    id: "warsaw",
    name: "Warsaw",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [52.22977, 21.01178],
    population: 1702139,
    enabled: true,
    importance: 4,
  },
  {
    id: "poznan",
    name: "Poznań",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [52.40692, 16.92993],
    population: 570352,
    enabled: true,
    importance: 4,
  },
  {
    id: "lublin",
    name: "Lublin",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [51.25000, 22.56667],
    population: 360044,
    enabled: true,
    importance: 4,
  },
  {
    id: "sopot",
    name: "Sopot",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [54.44180, 18.56003],
    population: 40142,
    enabled: true,
    importance: 4,
  },
  {
    id: "odz",
    name: "Łódź",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [51.75000, 19.46667],
    population: 768755,
    enabled: true,
    importance: 3,
  },
  {
    id: "szczecin",
    name: "Szczecin",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [53.42894, 14.55302],
    population: 407811,
    enabled: true,
    importance: 3,
  },
  {
    id: "bydgoszcz",
    name: "Bydgoszcz",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [53.12350, 18.00762],
    population: 366452,
    enabled: true,
    importance: 3,
  },
  {
    id: "katowice",
    name: "Katowice",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [50.25841, 19.02754],
    population: 317316,
    enabled: true,
    importance: 3,
  },
  {
    id: "bia-ystok",
    name: "Białystok",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [53.13333, 23.16433],
    population: 291855,
    enabled: true,
    importance: 3,
  },
  {
    id: "gdynia",
    name: "Gdynia",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [54.51889, 18.53188],
    population: 253730,
    enabled: true,
    importance: 3,
  },
  {
    id: "olsztyn",
    name: "Olsztyn",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [53.77995, 20.49416],
    population: 171803,
    enabled: true,
    importance: 3,
  },
  {
    id: "rzeszow",
    name: "Rzeszów",
    country: "Poland",
    countryCode: "PL",
    region: "Central Europe",
    position: [50.04132, 21.99901],
    population: 158382,
    enabled: true,
    importance: 3,
  },
  {
    id: "bratislava",
    name: "Bratislava",
    country: "Slovakia",
    countryCode: "SK",
    region: "Central Europe",
    position: [48.14816, 17.10674],
    population: 423737,
    enabled: true,
    importance: 5,
  },
  {
    id: "kosice",
    name: "Košice",
    country: "Slovakia",
    countryCode: "SK",
    region: "Central Europe",
    position: [48.71395, 21.25808],
    population: 236563,
    enabled: true,
    importance: 4,
  },
  {
    id: "banska-bystrica",
    name: "Banská Bystrica",
    country: "Slovakia",
    countryCode: "SK",
    region: "Central Europe",
    position: [48.73946, 19.15349],
    population: 82336,
    enabled: true,
    importance: 4,
  },
  {
    id: "nitra",
    name: "Nitra",
    country: "Slovakia",
    countryCode: "SK",
    region: "Central Europe",
    position: [48.30763, 18.08453],
    population: 86329,
    enabled: true,
    importance: 3,
  },
  {
    id: "zilina",
    name: "Žilina",
    country: "Slovakia",
    countryCode: "SK",
    region: "Central Europe",
    position: [49.22315, 18.73941],
    population: 85985,
    enabled: true,
    importance: 3,
  },
  {
    id: "ljubljana",
    name: "Ljubljana",
    country: "Slovenia",
    countryCode: "SI",
    region: "Central Europe",
    position: [46.05108, 14.50513],
    population: 272220,
    enabled: true,
    importance: 4,
  },
  {
    id: "maribor",
    name: "Maribor",
    country: "Slovenia",
    countryCode: "SI",
    region: "Central Europe",
    position: [46.55472, 15.64667],
    population: 95171,
    enabled: true,
    importance: 4,
  },
  {
    id: "koper",
    name: "Koper",
    country: "Slovenia",
    countryCode: "SI",
    region: "Central Europe",
    position: [45.54694, 13.72944],
    population: 24996,
    enabled: true,
    importance: 4,
  },
  {
    id: "ptuj",
    name: "Ptuj",
    country: "Slovenia",
    countryCode: "SI",
    region: "Central Europe",
    position: [46.42005, 15.87018],
    population: 18164,
    enabled: true,
    importance: 4,
  },
  {
    id: "celje",
    name: "Celje",
    country: "Slovenia",
    countryCode: "SI",
    region: "Central Europe",
    position: [46.23092, 15.26044],
    population: 37520,
    enabled: true,
    importance: 3,
  },
  {
    id: "lucerne",
    name: "Lucerne",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [47.05048, 8.30635],
    population: 57066,
    enabled: true,
    importance: 5,
  },
  {
    id: "zurich",
    name: "Zurich",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [47.36667, 8.55000],
    population: 341730,
    enabled: true,
    importance: 4,
  },
  {
    id: "geneva",
    name: "Geneva",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [46.20222, 6.14569],
    population: 183981,
    enabled: true,
    importance: 4,
  },
  {
    id: "bern",
    name: "Bern",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [46.94809, 7.44744],
    population: 121631,
    enabled: true,
    importance: 4,
  },
  {
    id: "lausanne",
    name: "Lausanne",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [46.51600, 6.63282],
    population: 116751,
    enabled: true,
    importance: 4,
  },
  {
    id: "thun",
    name: "Thun",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [46.75118, 7.62166],
    population: 42136,
    enabled: true,
    importance: 4,
  },
  {
    id: "lugano",
    name: "Lugano",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [46.01008, 8.96004],
    population: 26365,
    enabled: true,
    importance: 4,
  },
  {
    id: "montreux",
    name: "Montreux",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [46.43301, 6.91143],
    population: 22897,
    enabled: true,
    importance: 4,
  },
  {
    id: "basel",
    name: "Basel",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [47.55839, 7.57327],
    population: 164488,
    enabled: true,
    importance: 3,
  },
  {
    id: "st-gallen",
    name: "St. Gallen",
    country: "Switzerland",
    countryCode: "CH",
    region: "Central Europe",
    position: [47.42391, 9.37477],
    population: 70572,
    enabled: true,
    importance: 3,
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    region: "Northern Europe",
    position: [55.67594, 12.56553],
    population: 1153615,
    enabled: true,
    importance: 5,
  },
  {
    id: "aarhus",
    name: "Aarhus",
    country: "Denmark",
    countryCode: "DK",
    region: "Northern Europe",
    position: [56.15674, 10.21076],
    population: 237551,
    enabled: true,
    importance: 4,
  },
  {
    id: "odense",
    name: "Odense",
    country: "Denmark",
    countryCode: "DK",
    region: "Northern Europe",
    position: [55.39594, 10.38831],
    population: 145931,
    enabled: true,
    importance: 4,
  },
  {
    id: "roskilde",
    name: "Roskilde",
    country: "Denmark",
    countryCode: "DK",
    region: "Northern Europe",
    position: [55.64152, 12.08035],
    population: 44285,
    enabled: true,
    importance: 4,
  },
  {
    id: "helsing-r",
    name: "Helsingør",
    country: "Denmark",
    countryCode: "DK",
    region: "Northern Europe",
    position: [56.03606, 12.61360],
    population: 35048,
    enabled: true,
    importance: 4,
  },
  {
    id: "aalborg",
    name: "Aalborg",
    country: "Denmark",
    countryCode: "DK",
    region: "Northern Europe",
    position: [57.04800, 9.91870],
    population: 122219,
    enabled: true,
    importance: 3,
  },
  {
    id: "esbjerg",
    name: "Esbjerg",
    country: "Denmark",
    countryCode: "DK",
    region: "Northern Europe",
    position: [55.47028, 8.45187],
    population: 72205,
    enabled: true,
    importance: 3,
  },
  {
    id: "tallinn",
    name: "Tallinn",
    country: "Estonia",
    countryCode: "EE",
    region: "Northern Europe",
    position: [59.43696, 24.75353],
    population: 394024,
    enabled: true,
    importance: 4,
  },
  {
    id: "tartu",
    name: "Tartu",
    country: "Estonia",
    countryCode: "EE",
    region: "Northern Europe",
    position: [58.38062, 26.72509],
    population: 101092,
    enabled: true,
    importance: 4,
  },
  {
    id: "parnu",
    name: "Pärnu",
    country: "Estonia",
    countryCode: "EE",
    region: "Northern Europe",
    position: [58.38588, 24.49711],
    population: 44192,
    enabled: true,
    importance: 4,
  },
  {
    id: "narva",
    name: "Narva",
    country: "Estonia",
    countryCode: "EE",
    region: "Northern Europe",
    position: [59.37722, 28.19028],
    population: 66980,
    enabled: true,
    importance: 3,
  },
  {
    id: "rovaniemi",
    name: "Rovaniemi",
    country: "Finland",
    countryCode: "FI",
    region: "Northern Europe",
    position: [66.50000, 25.71667],
    population: 34781,
    enabled: true,
    importance: 5,
  },
  {
    id: "helsinki",
    name: "Helsinki",
    country: "Finland",
    countryCode: "FI",
    region: "Northern Europe",
    position: [60.16952, 24.93545],
    population: 558457,
    enabled: true,
    importance: 4,
  },
  {
    id: "tampere",
    name: "Tampere",
    country: "Finland",
    countryCode: "FI",
    region: "Northern Europe",
    position: [61.49911, 23.78712],
    population: 202687,
    enabled: true,
    importance: 4,
  },
  {
    id: "turku",
    name: "Turku",
    country: "Finland",
    countryCode: "FI",
    region: "Northern Europe",
    position: [60.45148, 22.26869],
    population: 175945,
    enabled: true,
    importance: 4,
  },
  {
    id: "porvoo",
    name: "Porvoo",
    country: "Finland",
    countryCode: "FI",
    region: "Northern Europe",
    position: [60.39233, 25.66507],
    population: 47192,
    enabled: true,
    importance: 4,
  },
  {
    id: "oulu",
    name: "Oulu",
    country: "Finland",
    countryCode: "FI",
    region: "Northern Europe",
    position: [65.01236, 25.46816],
    population: 128618,
    enabled: true,
    importance: 3,
  },
  {
    id: "jyvaskyla",
    name: "Jyväskylä",
    country: "Finland",
    countryCode: "FI",
    region: "Northern Europe",
    position: [62.24147, 25.72088],
    population: 85026,
    enabled: true,
    importance: 3,
  },
  {
    id: "reykjavik",
    name: "Reykjavík",
    country: "Iceland",
    countryCode: "IS",
    region: "Northern Europe",
    position: [64.13548, -21.89541],
    population: 118918,
    enabled: true,
    importance: 5,
  },
  {
    id: "akureyri",
    name: "Akureyri",
    country: "Iceland",
    countryCode: "IS",
    region: "Northern Europe",
    position: [65.68353, -18.08780],
    population: 17693,
    enabled: true,
    importance: 4,
  },
  {
    id: "kopavogur",
    name: "Kópavogur",
    country: "Iceland",
    countryCode: "IS",
    region: "Northern Europe",
    position: [64.11234, -21.91298],
    population: 31719,
    enabled: true,
    importance: 2,
  },
  {
    id: "riga",
    name: "Riga",
    country: "Latvia",
    countryCode: "LV",
    region: "Northern Europe",
    position: [56.94600, 24.10589],
    population: 742572,
    enabled: true,
    importance: 5,
  },
  {
    id: "jurmala",
    name: "Jūrmala",
    country: "Latvia",
    countryCode: "LV",
    region: "Northern Europe",
    position: [56.96800, 23.77038],
    population: 54088,
    enabled: true,
    importance: 4,
  },
  {
    id: "daugavpils",
    name: "Daugavpils",
    country: "Latvia",
    countryCode: "LV",
    region: "Northern Europe",
    position: [55.88333, 26.53333],
    population: 111564,
    enabled: true,
    importance: 3,
  },
  {
    id: "liepaja",
    name: "Liepāja",
    country: "Latvia",
    countryCode: "LV",
    region: "Northern Europe",
    position: [56.51667, 21.01667],
    population: 85132,
    enabled: true,
    importance: 3,
  },
  {
    id: "vilnius",
    name: "Vilnius",
    country: "Lithuania",
    countryCode: "LT",
    region: "Northern Europe",
    position: [54.68916, 25.27980],
    population: 542366,
    enabled: true,
    importance: 5,
  },
  {
    id: "kaunas",
    name: "Kaunas",
    country: "Lithuania",
    countryCode: "LT",
    region: "Northern Europe",
    position: [54.90272, 23.90961],
    population: 374643,
    enabled: true,
    importance: 4,
  },
  {
    id: "klaipeda",
    name: "Klaipėda",
    country: "Lithuania",
    countryCode: "LT",
    region: "Northern Europe",
    position: [55.70888, 21.14312],
    population: 192307,
    enabled: true,
    importance: 4,
  },
  {
    id: "siauliai",
    name: "Šiauliai",
    country: "Lithuania",
    countryCode: "LT",
    region: "Northern Europe",
    position: [55.93333, 23.31667],
    population: 130587,
    enabled: true,
    importance: 3,
  },
  {
    id: "panevezys",
    name: "Panevėžys",
    country: "Lithuania",
    countryCode: "LT",
    region: "Northern Europe",
    position: [55.73333, 24.35000],
    population: 117395,
    enabled: true,
    importance: 3,
  },
  {
    id: "bergen",
    name: "Bergen",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [60.39299, 5.32415],
    population: 213585,
    enabled: true,
    importance: 5,
  },
  {
    id: "troms",
    name: "Tromsø",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [69.64890, 18.95508],
    population: 52436,
    enabled: true,
    importance: 5,
  },
  {
    id: "alesund",
    name: "Ålesund",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [62.47225, 6.15492],
    population: 44096,
    enabled: true,
    importance: 5,
  },
  {
    id: "oslo",
    name: "Oslo",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [59.91273, 10.74609],
    population: 580000,
    enabled: true,
    importance: 4,
  },
  {
    id: "trondheim",
    name: "Trondheim",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [63.43049, 10.39506],
    population: 147139,
    enabled: true,
    importance: 4,
  },
  {
    id: "stavanger",
    name: "Stavanger",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [58.97005, 5.73332],
    population: 121610,
    enabled: true,
    importance: 4,
  },
  {
    id: "lillehammer",
    name: "Lillehammer",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [61.11514, 10.46628],
    population: 19096,
    enabled: true,
    importance: 4,
  },
  {
    id: "kristiansand",
    name: "Kristiansand",
    country: "Norway",
    countryCode: "NO",
    region: "Northern Europe",
    position: [58.14671, 7.99560],
    population: 63814,
    enabled: true,
    importance: 3,
  },
  {
    id: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [59.33258, 18.06490],
    population: 1253309,
    enabled: true,
    importance: 5,
  },
  {
    id: "visby",
    name: "Visby",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [57.64089, 18.29602],
    population: 21970,
    enabled: true,
    importance: 5,
  },
  {
    id: "gothenburg",
    name: "Gothenburg",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [57.70716, 11.96679],
    population: 504084,
    enabled: true,
    importance: 4,
  },
  {
    id: "malmo",
    name: "Malmö",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [55.60587, 13.00073],
    population: 261548,
    enabled: true,
    importance: 4,
  },
  {
    id: "uppsala",
    name: "Uppsala",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [59.85882, 17.63889],
    population: 127734,
    enabled: true,
    importance: 4,
  },
  {
    id: "lund",
    name: "Lund",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [55.70584, 13.19321],
    population: 76263,
    enabled: true,
    importance: 4,
  },
  {
    id: "kiruna",
    name: "Kiruna",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [67.85572, 20.22513],
    population: 18154,
    enabled: true,
    importance: 4,
  },
  {
    id: "orebro",
    name: "Örebro",
    country: "Sweden",
    countryCode: "SE",
    region: "Northern Europe",
    position: [59.27412, 15.20660],
    population: 98573,
    enabled: true,
    importance: 3,
  },
  {
    id: "tirana",
    name: "Tirana",
    country: "Albania",
    countryCode: "AL",
    region: "Balkans",
    position: [41.32750, 19.81889],
    population: 374801,
    enabled: true,
    importance: 5,
  },
  {
    id: "berat",
    name: "Berat",
    country: "Albania",
    countryCode: "AL",
    region: "Balkans",
    position: [40.70583, 19.95222],
    population: 46866,
    enabled: true,
    importance: 5,
  },
  {
    id: "gjirokaster",
    name: "Gjirokastër",
    country: "Albania",
    countryCode: "AL",
    region: "Balkans",
    position: [40.07583, 20.13889],
    population: 23437,
    enabled: true,
    importance: 5,
  },
  {
    id: "vlore",
    name: "Vlorë",
    country: "Albania",
    countryCode: "AL",
    region: "Balkans",
    position: [40.46667, 19.48972],
    population: 89546,
    enabled: true,
    importance: 4,
  },
  {
    id: "shkoder",
    name: "Shkodër",
    country: "Albania",
    countryCode: "AL",
    region: "Balkans",
    position: [42.06828, 19.51258],
    population: 88245,
    enabled: true,
    importance: 4,
  },
  {
    id: "sarajevo",
    name: "Sarajevo",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
    region: "Balkans",
    position: [43.84864, 18.35644],
    population: 696731,
    enabled: true,
    importance: 5,
  },
  {
    id: "mostar",
    name: "Mostar",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
    region: "Balkans",
    position: [43.34333, 17.80806],
    population: 104518,
    enabled: true,
    importance: 5,
  },
  {
    id: "banja-luka",
    name: "Banja Luka",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
    region: "Balkans",
    position: [44.77842, 17.19386],
    population: 221106,
    enabled: true,
    importance: 4,
  },
  {
    id: "travnik",
    name: "Travnik",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
    region: "Balkans",
    position: [44.22637, 17.66583],
    population: 31127,
    enabled: true,
    importance: 4,
  },
  {
    id: "tuzla",
    name: "Tuzla",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
    region: "Balkans",
    position: [44.53842, 18.66709],
    population: 142486,
    enabled: true,
    importance: 3,
  },
  {
    id: "sofia",
    name: "Sofia",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [42.69751, 23.32415],
    population: 1152556,
    enabled: true,
    importance: 5,
  },
  {
    id: "plovdiv",
    name: "Plovdiv",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [42.15000, 24.75000],
    population: 340494,
    enabled: true,
    importance: 5,
  },
  {
    id: "veliko-turnovo",
    name: "Veliko Tŭrnovo",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [43.08124, 25.62904],
    population: 66217,
    enabled: true,
    importance: 5,
  },
  {
    id: "varna",
    name: "Varna",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [43.21667, 27.91667],
    population: 312770,
    enabled: true,
    importance: 4,
  },
  {
    id: "burgas",
    name: "Burgas",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [42.50606, 27.46781],
    population: 195966,
    enabled: true,
    importance: 4,
  },
  {
    id: "ruse",
    name: "Ruse",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [43.85639, 25.97083],
    population: 156238,
    enabled: true,
    importance: 3,
  },
  {
    id: "stara-zagora",
    name: "Stara Zagora",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [42.43278, 25.64194],
    population: 143431,
    enabled: true,
    importance: 3,
  },
  {
    id: "pleven",
    name: "Pleven",
    country: "Bulgaria",
    countryCode: "BG",
    region: "Balkans",
    position: [43.41667, 24.61667],
    population: 118675,
    enabled: true,
    importance: 2,
  },
  {
    id: "split",
    name: "Split",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [43.50891, 16.43915],
    population: 176314,
    enabled: true,
    importance: 5,
  },
  {
    id: "zadar",
    name: "Zadar",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [44.11972, 15.24222],
    population: 71258,
    enabled: true,
    importance: 5,
  },
  {
    id: "dubrovnik",
    name: "Dubrovnik",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [42.64807, 18.09216],
    population: 28428,
    enabled: true,
    importance: 5,
  },
  {
    id: "zagreb",
    name: "Zagreb",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [45.81444, 15.97798],
    population: 698966,
    enabled: true,
    importance: 4,
  },
  {
    id: "pula",
    name: "Pula",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [44.86833, 13.84806],
    population: 59078,
    enabled: true,
    importance: 4,
  },
  {
    id: "sibenik",
    name: "Šibenik",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [43.72722, 15.90583],
    population: 37112,
    enabled: true,
    importance: 4,
  },
  {
    id: "rijeka",
    name: "Rijeka",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [45.34306, 14.40917],
    population: 141172,
    enabled: true,
    importance: 3,
  },
  {
    id: "osijek",
    name: "Osijek",
    country: "Croatia",
    countryCode: "HR",
    region: "Balkans",
    position: [45.55111, 18.69389],
    population: 88140,
    enabled: true,
    importance: 3,
  },
  {
    id: "athens",
    name: "Athens",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [37.97945, 23.71622],
    population: 664046,
    enabled: true,
    importance: 5,
  },
  {
    id: "rhodes",
    name: "Rhodes",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [36.43556, 28.22199],
    population: 56128,
    enabled: true,
    importance: 5,
  },
  {
    id: "chania",
    name: "Chania",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [35.51124, 24.02921],
    population: 53910,
    enabled: true,
    importance: 5,
  },
  {
    id: "corfu",
    name: "Corfu",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [39.62069, 19.91975],
    population: 27003,
    enabled: true,
    importance: 5,
  },
  {
    id: "thessaloniki",
    name: "Thessaloniki",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [40.64361, 22.93086],
    population: 354290,
    enabled: true,
    importance: 4,
  },
  {
    id: "heraklion",
    name: "Heraklion",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [35.32787, 25.14341],
    population: 137154,
    enabled: true,
    importance: 4,
  },
  {
    id: "volos",
    name: "Volos",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [39.36103, 22.94248],
    population: 86048,
    enabled: true,
    importance: 4,
  },
  {
    id: "ioannina",
    name: "Ioannina",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [39.66486, 20.85189],
    population: 65574,
    enabled: true,
    importance: 4,
  },
  {
    id: "kalamata",
    name: "Kalamata",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [37.03913, 22.11265],
    population: 54100,
    enabled: true,
    importance: 4,
  },
  {
    id: "kavala",
    name: "Kavala",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [40.93959, 24.40687],
    population: 54027,
    enabled: true,
    importance: 4,
  },
  {
    id: "patras",
    name: "Patras",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [38.24444, 21.73444],
    population: 168034,
    enabled: true,
    importance: 3,
  },
  {
    id: "larissa",
    name: "Larissa",
    country: "Greece",
    countryCode: "GR",
    region: "Balkans",
    position: [39.63689, 22.41761],
    population: 144651,
    enabled: true,
    importance: 3,
  },
  {
    id: "pristina",
    name: "Pristina",
    country: "Kosovo",
    countryCode: "XK",
    region: "Balkans",
    position: [42.67272, 21.16688],
    population: 550000,
    enabled: true,
    importance: 4,
  },
  {
    id: "prizren",
    name: "Prizren",
    country: "Kosovo",
    countryCode: "XK",
    region: "Balkans",
    position: [42.21389, 20.73972],
    population: 171464,
    enabled: true,
    importance: 4,
  },
  {
    id: "peje",
    name: "Pejë",
    country: "Kosovo",
    countryCode: "XK",
    region: "Balkans",
    position: [42.65913, 20.28828],
    population: 81800,
    enabled: true,
    importance: 3,
  },
  {
    id: "budva",
    name: "Budva",
    country: "Montenegro",
    countryCode: "ME",
    region: "Balkans",
    position: [42.28639, 18.84000],
    population: 18000,
    enabled: true,
    importance: 5,
  },
  {
    id: "herceg-novi",
    name: "Herceg Novi",
    country: "Montenegro",
    countryCode: "ME",
    region: "Balkans",
    position: [42.45306, 18.53750],
    population: 19536,
    enabled: true,
    importance: 4,
  },
  {
    id: "podgorica",
    name: "Podgorica",
    country: "Montenegro",
    countryCode: "ME",
    region: "Balkans",
    position: [42.44111, 19.26361],
    population: 136473,
    enabled: true,
    importance: 3,
  },
  {
    id: "ohrid",
    name: "Ohrid",
    country: "North Macedonia",
    countryCode: "MK",
    region: "Balkans",
    position: [41.11722, 20.80194],
    population: 54908,
    enabled: true,
    importance: 5,
  },
  {
    id: "skopje",
    name: "Skopje",
    country: "North Macedonia",
    countryCode: "MK",
    region: "Balkans",
    position: [41.99646, 21.43141],
    population: 474889,
    enabled: true,
    importance: 4,
  },
  {
    id: "bitola",
    name: "Bitola",
    country: "North Macedonia",
    countryCode: "MK",
    region: "Balkans",
    position: [41.03143, 21.33474],
    population: 86528,
    enabled: true,
    importance: 4,
  },
  {
    id: "cluj-napoca",
    name: "Cluj-Napoca",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [46.76667, 23.60000],
    population: 316748,
    enabled: true,
    importance: 5,
  },
  {
    id: "brasov",
    name: "Braşov",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [45.64861, 25.60613],
    population: 276088,
    enabled: true,
    importance: 5,
  },
  {
    id: "sibiu",
    name: "Sibiu",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [45.80000, 24.15000],
    population: 151894,
    enabled: true,
    importance: 5,
  },
  {
    id: "sighisoara",
    name: "Sighișoara",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [46.22141, 24.79279],
    population: 34537,
    enabled: true,
    importance: 5,
  },
  {
    id: "iasi",
    name: "Iaşi",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [47.16667, 27.60000],
    population: 318012,
    enabled: true,
    importance: 4,
  },
  {
    id: "timisoara",
    name: "Timişoara",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [45.75372, 21.22571],
    population: 315053,
    enabled: true,
    importance: 4,
  },
  {
    id: "constanta",
    name: "Constanţa",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [44.18073, 28.63432],
    population: 303399,
    enabled: true,
    importance: 4,
  },
  {
    id: "oradea",
    name: "Oradea",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [47.04580, 21.91833],
    population: 206614,
    enabled: true,
    importance: 4,
  },
  {
    id: "targu-mures",
    name: "Târgu-Mureş",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [46.54245, 24.55747],
    population: 146863,
    enabled: true,
    importance: 4,
  },
  {
    id: "suceava",
    name: "Suceava",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [47.63333, 26.25000],
    population: 105796,
    enabled: true,
    importance: 4,
  },
  {
    id: "craiova",
    name: "Craiova",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [44.31667, 23.80000],
    population: 304142,
    enabled: true,
    importance: 3,
  },
  {
    id: "arad",
    name: "Arad",
    country: "Romania",
    countryCode: "RO",
    region: "Balkans",
    position: [46.18333, 21.31667],
    population: 169065,
    enabled: true,
    importance: 3,
  },
  {
    id: "belgrade",
    name: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    region: "Balkans",
    position: [44.80401, 20.46513],
    population: 1273651,
    enabled: true,
    importance: 5,
  },
  {
    id: "novi-sad",
    name: "Novi Sad",
    country: "Serbia",
    countryCode: "RS",
    region: "Balkans",
    position: [45.25167, 19.83694],
    population: 215400,
    enabled: true,
    importance: 5,
  },
  {
    id: "nis",
    name: "Niš",
    country: "Serbia",
    countryCode: "RS",
    region: "Balkans",
    position: [43.32472, 21.90333],
    population: 250000,
    enabled: true,
    importance: 4,
  },
  {
    id: "subotica",
    name: "Subotica",
    country: "Serbia",
    countryCode: "RS",
    region: "Balkans",
    position: [46.10000, 19.66667],
    population: 100000,
    enabled: true,
    importance: 4,
  },
  {
    id: "kragujevac",
    name: "Kragujevac",
    country: "Serbia",
    countryCode: "RS",
    region: "Balkans",
    position: [44.01667, 20.91667],
    population: 147473,
    enabled: true,
    importance: 3,
  },
  {
    id: "kraljevo",
    name: "Kraljevo",
    country: "Serbia",
    countryCode: "RS",
    region: "Balkans",
    position: [43.72583, 20.68944],
    population: 82846,
    enabled: true,
    importance: 3,
  },
  {
    id: "uzice",
    name: "Užice",
    country: "Serbia",
    countryCode: "RS",
    region: "Balkans",
    position: [43.85861, 19.84878],
    population: 63577,
    enabled: true,
    importance: 3,
  },
  {
    id: "chisinau",
    name: "Chişinău",
    country: "Moldova",
    countryCode: "MD",
    region: "Eastern Europe",
    position: [47.00556, 28.85750],
    population: 635994,
    enabled: true,
    importance: 4,
  },
  {
    id: "tiraspol",
    name: "Tiraspol",
    country: "Moldova",
    countryCode: "MD",
    region: "Eastern Europe",
    position: [46.84274, 29.62909],
    population: 157000,
    enabled: true,
    importance: 2,
  },
  {
    id: "paphos",
    name: "Paphos",
    country: "Cyprus",
    countryCode: "CY",
    region: "Eastern Mediterranean",
    position: [34.77679, 32.42451],
    population: 35961,
    enabled: true,
    importance: 5,
  },
  {
    id: "nicosia",
    name: "Nicosia",
    country: "Cyprus",
    countryCode: "CY",
    region: "Eastern Mediterranean",
    position: [35.17531, 33.36420],
    population: 200452,
    enabled: true,
    importance: 4,
  },
  {
    id: "limassol",
    name: "Limassol",
    country: "Cyprus",
    countryCode: "CY",
    region: "Eastern Mediterranean",
    position: [34.68406, 33.03794],
    population: 154000,
    enabled: true,
    importance: 4,
  },
  {
    id: "larnaca",
    name: "Larnaca",
    country: "Cyprus",
    countryCode: "CY",
    region: "Eastern Mediterranean",
    position: [34.92291, 33.62330],
    population: 72000,
    enabled: true,
    importance: 4,
  },
  {
    id: "istanbul",
    name: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [41.01384, 28.94966],
    population: 11174257,
    enabled: true,
    importance: 5,
  },
  {
    id: "antalya",
    name: "Antalya",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [36.90812, 30.69556],
    population: 758188,
    enabled: true,
    importance: 5,
  },
  {
    id: "bodrum",
    name: "Bodrum",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [37.03833, 27.42917],
    population: 39317,
    enabled: true,
    importance: 5,
  },
  {
    id: "ankara",
    name: "Ankara",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [39.91987, 32.85427],
    population: 3517182,
    enabled: true,
    importance: 4,
  },
  {
    id: "izmir",
    name: "İzmir",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [38.41273, 27.13838],
    population: 2500603,
    enabled: true,
    importance: 4,
  },
  {
    id: "bursa",
    name: "Bursa",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [40.19559, 29.06013],
    population: 1412701,
    enabled: true,
    importance: 4,
  },
  {
    id: "edirne",
    name: "Edirne",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [41.67719, 26.55597],
    population: 126470,
    enabled: true,
    importance: 4,
  },
  {
    id: "canakkale",
    name: "Çanakkale",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [40.15552, 26.41271],
    population: 87791,
    enabled: true,
    importance: 4,
  },
  {
    id: "konya",
    name: "Konya",
    country: "Türkiye",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    position: [37.87135, 32.48464],
    population: 875530,
    enabled: true,
    importance: 3,
  },
];

export const connectionOverrides: ConnectionOverride[] = [
  {
    fromCityId: "barcelona",
    toCityId: "valencia",
    transport: "train",
    estimatedPriceEur: 25,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "zaragoza",
    transport: "train",
    estimatedPriceEur: 30,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "madrid",
    transport: "train",
    estimatedPriceEur: 45,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "montpellier",
    transport: "train",
    estimatedPriceEur: 38,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "palma",
    transport: "plane",
    estimatedPriceEur: 35,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "valencia",
    toCityId: "alicante",
    transport: "train",
    estimatedPriceEur: 18,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "valencia",
    toCityId: "madrid",
    transport: "train",
    estimatedPriceEur: 32,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
];

export function getPopulationBand(
  population: number,
): PopulationBand {
  if (population < 100_000) {
    return "small";
  }

  if (population < 500_000) {
    return "medium";
  }

  if (population < 1_500_000) {
    return "large";
  }

  return "major";
}

export function getCityById(cityId: string) {
  return cities.find((city) => city.id === cityId);
}
