export type RoutePoint = [number, number];

export type TransportType =
  | "train"
  | "plane"
  | "bus"
  | "ferry";

export type City = {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  position: RoutePoint;
  enabled: boolean;
};

export type ConnectionOverride = {
  fromCityId: string;
  toCityId: string;
  transport: TransportType;
  estimatedPriceEur: number;
  bidirectional: boolean;
  enabled: boolean;
  dataStatus: "prototype" | "verified";
  notes: string;
};

export const recommendationConfig = {
  recommendationCount: 5,
  minimumDistanceKm: 40,
  maximumDistanceKm: 550,
  trainWaypointSpacingKm: 75,
  trainRandomness: 0.06,
  planeCurveStrength: 0.18,
} as const;

export const cities: City[] = [
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    position: [41.38879, 2.15899],
    enabled: true,
  },
  {
    id: "madrid",
    name: "Madrid",
    country: "Spain",
    countryCode: "ES",
    position: [40.41650, -3.70256],
    enabled: true,
  },
  {
    id: "valencia",
    name: "Valencia",
    country: "Spain",
    countryCode: "ES",
    position: [39.47391, -0.37966],
    enabled: true,
  },
  {
    id: "seville",
    name: "Seville",
    country: "Spain",
    countryCode: "ES",
    position: [37.38283, -5.97317],
    enabled: true,
  },
  {
    id: "malaga",
    name: "Malaga",
    country: "Spain",
    countryCode: "ES",
    position: [36.72016, -4.42034],
    enabled: true,
  },
  {
    id: "granada",
    name: "Granada",
    country: "Spain",
    countryCode: "ES",
    position: [37.18817, -3.60667],
    enabled: true,
  },
  {
    id: "zaragoza",
    name: "Zaragoza",
    country: "Spain",
    countryCode: "ES",
    position: [41.65606, -0.87734],
    enabled: true,
  },
  {
    id: "bilbao",
    name: "Bilbao",
    country: "Spain",
    countryCode: "ES",
    position: [43.26271, -2.92528],
    enabled: true,
  },
  {
    id: "san-sebastian",
    name: "San Sebastian",
    country: "Spain",
    countryCode: "ES",
    position: [43.31283, -1.97499],
    enabled: true,
  },
  {
    id: "alicante",
    name: "Alicante",
    country: "Spain",
    countryCode: "ES",
    position: [38.34517, -0.48149],
    enabled: true,
  },
  {
    id: "palma",
    name: "Palma",
    country: "Spain",
    countryCode: "ES",
    position: [39.56939, 2.65024],
    enabled: true,
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    position: [38.72509, -9.14980],
    enabled: true,
  },
  {
    id: "porto",
    name: "Porto",
    country: "Portugal",
    countryCode: "PT",
    position: [41.14850, -8.61097],
    enabled: true,
  },
  {
    id: "faro",
    name: "Faro",
    country: "Portugal",
    countryCode: "PT",
    position: [37.01869, -7.92716],
    enabled: true,
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    position: [48.85341, 2.34880],
    enabled: true,
  },
  {
    id: "lyon",
    name: "Lyon",
    country: "France",
    countryCode: "FR",
    position: [45.74906, 4.84789],
    enabled: true,
  },
  {
    id: "marseille",
    name: "Marseille",
    country: "France",
    countryCode: "FR",
    position: [43.29695, 5.38107],
    enabled: true,
  },
  {
    id: "nice",
    name: "Nice",
    country: "France",
    countryCode: "FR",
    position: [43.70313, 7.26608],
    enabled: true,
  },
  {
    id: "toulouse",
    name: "Toulouse",
    country: "France",
    countryCode: "FR",
    position: [43.60426, 1.44367],
    enabled: true,
  },
  {
    id: "bordeaux",
    name: "Bordeaux",
    country: "France",
    countryCode: "FR",
    position: [44.84124, -0.58046],
    enabled: true,
  },
  {
    id: "montpellier",
    name: "Montpellier",
    country: "France",
    countryCode: "FR",
    position: [43.61093, 3.87635],
    enabled: true,
  },
  {
    id: "strasbourg",
    name: "Strasbourg",
    country: "France",
    countryCode: "FR",
    position: [48.58392, 7.74553],
    enabled: true,
  },
  {
    id: "lille",
    name: "Lille",
    country: "France",
    countryCode: "FR",
    position: [50.63391, 3.05512],
    enabled: true,
  },
  {
    id: "nantes",
    name: "Nantes",
    country: "France",
    countryCode: "FR",
    position: [47.21725, -1.55336],
    enabled: true,
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    position: [51.50853, -0.12574],
    enabled: true,
  },
  {
    id: "edinburgh",
    name: "Edinburgh",
    country: "United Kingdom",
    countryCode: "GB",
    position: [55.95206, -3.19648],
    enabled: true,
  },
  {
    id: "glasgow",
    name: "Glasgow",
    country: "United Kingdom",
    countryCode: "GB",
    position: [55.86515, -4.25763],
    enabled: true,
  },
  {
    id: "manchester",
    name: "Manchester",
    country: "United Kingdom",
    countryCode: "GB",
    position: [53.48095, -2.23743],
    enabled: true,
  },
  {
    id: "liverpool",
    name: "Liverpool",
    country: "United Kingdom",
    countryCode: "GB",
    position: [53.41058, -2.97794],
    enabled: true,
  },
  {
    id: "bristol",
    name: "Bristol",
    country: "United Kingdom",
    countryCode: "GB",
    position: [51.45523, -2.59665],
    enabled: true,
  },
  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    position: [53.33306, -6.24889],
    enabled: true,
  },
  {
    id: "belfast",
    name: "Belfast",
    country: "United Kingdom",
    countryCode: "GB",
    position: [54.59682, -5.92541],
    enabled: true,
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    position: [52.37403, 4.88969],
    enabled: true,
  },
  {
    id: "rotterdam",
    name: "Rotterdam",
    country: "Netherlands",
    countryCode: "NL",
    position: [51.92250, 4.47917],
    enabled: true,
  },
  {
    id: "brussels",
    name: "Brussels",
    country: "Belgium",
    countryCode: "BE",
    position: [50.85045, 4.34878],
    enabled: true,
  },
  {
    id: "antwerp",
    name: "Antwerp",
    country: "Belgium",
    countryCode: "BE",
    position: [51.22047, 4.40026],
    enabled: true,
  },
  {
    id: "bruges",
    name: "Bruges",
    country: "Belgium",
    countryCode: "BE",
    position: [51.20892, 3.22424],
    enabled: true,
  },
  {
    id: "luxembourg",
    name: "Luxembourg",
    country: "Luxembourg",
    countryCode: "LU",
    position: [49.60982, 6.13268],
    enabled: true,
  },
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    position: [52.52437, 13.41053],
    enabled: true,
  },
  {
    id: "munich",
    name: "Munich",
    country: "Germany",
    countryCode: "DE",
    position: [48.13743, 11.57549],
    enabled: true,
  },
  {
    id: "hamburg",
    name: "Hamburg",
    country: "Germany",
    countryCode: "DE",
    position: [53.55073, 9.99302],
    enabled: true,
  },
  {
    id: "cologne",
    name: "Cologne",
    country: "Germany",
    countryCode: "DE",
    position: [50.93333, 6.95000],
    enabled: true,
  },
  {
    id: "frankfurt",
    name: "Frankfurt",
    country: "Germany",
    countryCode: "DE",
    position: [50.11552, 8.68417],
    enabled: true,
  },
  {
    id: "stuttgart",
    name: "Stuttgart",
    country: "Germany",
    countryCode: "DE",
    position: [48.78232, 9.17702],
    enabled: true,
  },
  {
    id: "nuremberg",
    name: "Nuremberg",
    country: "Germany",
    countryCode: "DE",
    position: [49.45421, 11.07752],
    enabled: true,
  },
  {
    id: "dresden",
    name: "Dresden",
    country: "Germany",
    countryCode: "DE",
    position: [51.05089, 13.73832],
    enabled: true,
  },
  {
    id: "leipzig",
    name: "Leipzig",
    country: "Germany",
    countryCode: "DE",
    position: [51.33962, 12.37129],
    enabled: true,
  },
  {
    id: "zurich",
    name: "Zurich",
    country: "Switzerland",
    countryCode: "CH",
    position: [47.36667, 8.55000],
    enabled: true,
  },
  {
    id: "geneva",
    name: "Geneva",
    country: "Switzerland",
    countryCode: "CH",
    position: [46.20222, 6.14569],
    enabled: true,
  },
  {
    id: "basel",
    name: "Basel",
    country: "Switzerland",
    countryCode: "CH",
    position: [47.55839, 7.57327],
    enabled: true,
  },
  {
    id: "bern",
    name: "Bern",
    country: "Switzerland",
    countryCode: "CH",
    position: [46.94809, 7.44744],
    enabled: true,
  },
  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    countryCode: "AT",
    position: [48.20849, 16.37208],
    enabled: true,
  },
  {
    id: "salzburg",
    name: "Salzburg",
    country: "Austria",
    countryCode: "AT",
    position: [47.79941, 13.04399],
    enabled: true,
  },
  {
    id: "innsbruck",
    name: "Innsbruck",
    country: "Austria",
    countryCode: "AT",
    position: [47.26266, 11.39454],
    enabled: true,
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    position: [41.89193, 12.51133],
    enabled: true,
  },
  {
    id: "milan",
    name: "Milan",
    country: "Italy",
    countryCode: "IT",
    position: [45.46427, 9.18951],
    enabled: true,
  },
  {
    id: "venice",
    name: "Venice",
    country: "Italy",
    countryCode: "IT",
    position: [45.43713, 12.33265],
    enabled: true,
  },
  {
    id: "florence",
    name: "Florence",
    country: "Italy",
    countryCode: "IT",
    position: [43.77925, 11.24626],
    enabled: true,
  },
  {
    id: "bologna",
    name: "Bologna",
    country: "Italy",
    countryCode: "IT",
    position: [44.49381, 11.33875],
    enabled: true,
  },
  {
    id: "naples",
    name: "Naples",
    country: "Italy",
    countryCode: "IT",
    position: [40.85216, 14.26811],
    enabled: true,
  },
  {
    id: "turin",
    name: "Turin",
    country: "Italy",
    countryCode: "IT",
    position: [45.07049, 7.68682],
    enabled: true,
  },
  {
    id: "genoa",
    name: "Genoa",
    country: "Italy",
    countryCode: "IT",
    position: [44.40478, 8.94439],
    enabled: true,
  },
  {
    id: "verona",
    name: "Verona",
    country: "Italy",
    countryCode: "IT",
    position: [45.43854, 10.99380],
    enabled: true,
  },
  {
    id: "bari",
    name: "Bari",
    country: "Italy",
    countryCode: "IT",
    position: [41.12066, 16.86982],
    enabled: true,
  },
  {
    id: "palermo",
    name: "Palermo",
    country: "Italy",
    countryCode: "IT",
    position: [38.11660, 13.36360],
    enabled: true,
  },
  {
    id: "prague",
    name: "Prague",
    country: "Czechia",
    countryCode: "CZ",
    position: [50.08804, 14.42076],
    enabled: true,
  },
  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    position: [47.49835, 19.04045],
    enabled: true,
  },
  {
    id: "krakow",
    name: "Krakow",
    country: "Poland",
    countryCode: "PL",
    position: [50.06143, 19.93658],
    enabled: true,
  },
  {
    id: "warsaw",
    name: "Warsaw",
    country: "Poland",
    countryCode: "PL",
    position: [52.22977, 21.01178],
    enabled: true,
  },
  {
    id: "ljubljana",
    name: "Ljubljana",
    country: "Slovenia",
    countryCode: "SI",
    position: [46.05108, 14.50513],
    enabled: true,
  },
  {
    id: "zagreb",
    name: "Zagreb",
    country: "Croatia",
    countryCode: "HR",
    position: [45.81444, 15.97798],
    enabled: true,
  },
  {
    id: "split",
    name: "Split",
    country: "Croatia",
    countryCode: "HR",
    position: [43.50891, 16.43915],
    enabled: true,
  },
  {
    id: "dubrovnik",
    name: "Dubrovnik",
    country: "Croatia",
    countryCode: "HR",
    position: [42.64125, 18.10909],
    enabled: true,
  },
  {
    id: "athens",
    name: "Athens",
    country: "Greece",
    countryCode: "GR",
    position: [37.98376, 23.72784],
    enabled: true,
  },
  {
    id: "thessaloniki",
    name: "Thessaloniki",
    country: "Greece",
    countryCode: "GR",
    position: [40.64072, 22.93493],
    enabled: true,
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    position: [55.67594, 12.56553],
    enabled: true,
  },
  {
    id: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    position: [59.32938, 18.06871],
    enabled: true,
  },
  {
    id: "oslo",
    name: "Oslo",
    country: "Norway",
    countryCode: "NO",
    position: [59.91273, 10.74609],
    enabled: true,
  },
  {
    id: "helsinki",
    name: "Helsinki",
    country: "Finland",
    countryCode: "FI",
    position: [60.16952, 24.93545],
    enabled: true,
  },
  {
    id: "tallinn",
    name: "Tallinn",
    country: "Estonia",
    countryCode: "EE",
    position: [59.43696, 24.75353],
    enabled: true,
  },
];

export const connectionOverrides: ConnectionOverride[] = [
  {
    fromCityId: "barcelona",
    toCityId: "valencia",
    transport: "train",
    estimatedPriceEur: 25,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "zaragoza",
    transport: "train",
    estimatedPriceEur: 30,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "madrid",
    transport: "train",
    estimatedPriceEur: 45,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "montpellier",
    transport: "train",
    estimatedPriceEur: 38,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "barcelona",
    toCityId: "palma",
    transport: "plane",
    estimatedPriceEur: 35,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "valencia",
    toCityId: "alicante",
    transport: "train",
    estimatedPriceEur: 18,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
  {
    fromCityId: "valencia",
    toCityId: "madrid",
    transport: "train",
    estimatedPriceEur: 32,
    bidirectional: true,
    enabled: true,
    dataStatus: "prototype",
    notes: "Existing prototype route",
  },
];

export function getCityById(cityId: string) {
  return cities.find((city) => city.id === cityId);
}
